struct tagResource;
struct tagSaveData;
struct tagSaveFile;
struct tagSaveDir;
struct tagEntryList;

typedef struct tagResource Resource;
typedef struct tagSaveData SaveData;
typedef struct tagSaveFile SaveFile;
typedef struct tagSaveDir SaveDir;
typedef struct tagEntryList EntryList;

Resource *save3ds_resource_create(const char *boot9_path, const char *movable_path, const char *sd_path, const char *nand_path);
void save3ds_resource_release(Resource *resource);
SaveData *save3ds_open_sd_save(Resource *resource, unsigned long long id);
SaveData *save3ds_open_nand_save(Resource *resource, unsigned int id);
SaveData *save3ds_open_bare_save(Resource *resource, const char *path);
void save3ds_save_release(SaveData *save);
void save3ds_save_commit(SaveData *save);
SaveFile *save3ds_save_file_open_ino(SaveData *save, unsigned ino);
void save3ds_save_file_release(SaveFile *file);
int save3ds_save_file_rename(SaveFile *file, SaveDir *parent, const char *name);
unsigned save3ds_save_file_get_parent_ino(SaveFile *file);
unsigned save3ds_save_file_get_ino(SaveFile *file);
int save3ds_save_file_delete(SaveFile *file);
int save3ds_save_file_resize(SaveFile *file, unsigned long long len);
unsigned long long save3ds_save_file_len(SaveFile *file);
int save3ds_save_file_read(SaveFile *file, unsigned long long pos, unsigned long long len, char *buf);
int save3ds_save_file_write(SaveFile *file, unsigned long long pos, unsigned long long len, const char *buf);
SaveDir *save3ds_save_dir_open_root(SaveData *save);
SaveDir *save3ds_save_dir_open_ino(SaveData *save, unsigned ino);
void save3ds_save_dir_release(SaveDir *dir);
int save3ds_save_dir_rename(SaveDir *dir, SaveDir *parent, const char *name);
unsigned save3ds_save_dir_get_parent_ino(SaveDir *dir);
unsigned save3ds_save_dir_get_ino(SaveDir *dir);
int save3ds_save_dir_delete(SaveDir *dir);
SaveDir *save3ds_save_dir_open_sub_dir(SaveDir *dir, const char *name);
SaveFile *save3ds_save_dir_open_sub_file(SaveDir *dir, const char *name);
SaveDir *save3ds_save_dir_new_sub_dir(SaveDir *dir, const char *name);
SaveFile *save3ds_save_dir_new_sub_file(SaveDir *dir, const char *name, unsigned long long len);
EntryList *save3ds_save_dir_list_sub_dir(SaveDir *dir);
EntryList *save3ds_save_dir_list_sub_file(SaveDir *dir);
void save3ds_entry_list_release(EntryList *list);
unsigned save3ds_entry_list_len(EntryList *list);
void save3ds_entry_list_get(EntryList *list, unsigned index, char *name, unsigned *ino);
